# Generated by Django 6.0.3 on 2026-03-23 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name (derived from filename or repo)', max_length=255)),
                ('upload_type', models.CharField(choices=[('zip', 'ZIP Upload'), ('git', 'Git Repository')], max_length=10)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='projects/uploads/')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('extracted_path', models.CharField(blank=True, help_text='Local filesystem path to the extracted/cloned project', max_length=1000, null=True)),
                ('total_files', models.IntegerField(default=0, help_text='Number of relevant files found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_path', models.CharField(help_text='Relative directory path', max_length=1000)),
                ('summary', models.TextField(blank=True, default='')),
                ('file_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_summaries', to='analyzer.project')),
            ],
            options={
                'verbose_name': 'Module Summary',
                'verbose_name_plural': 'Module Summaries',
                'ordering': ['module_path'],
            },
        ),
        migrations.CreateModel(
            name='FileSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path within the project', max_length=1000)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_summaries', to='analyzer.project')),
            ],
            options={
                'verbose_name': 'File Summary',
                'verbose_name_plural': 'File Summaries',
                'ordering': ['file_path'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('progress_message', models.CharField(blank=True, default='', help_text='Human-readable progress description', max_length=500)),
                ('progress_percent', models.IntegerField(default=0, help_text='Estimated completion percentage (0-100)')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job', to='analyzer.project')),
            ],
            options={
                'verbose_name': 'Analysis Job',
                'verbose_name_plural': 'Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_type', models.CharField(choices=[('overview', 'Project Overview'), ('architecture', 'Architecture Explanation'), ('workflow', 'Workflow Explanation'), ('usecase_diagram', 'Use Case Diagram (Mermaid)'), ('user_manual', 'User Manual')], max_length=30)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='analyzer.project')),
            ],
            options={
                'verbose_name': 'Project Output',
                'verbose_name_plural': 'Project Outputs',
                'ordering': ['output_type'],
                'unique_together': {('project', 'output_type')},
            },
        ),
    ]
