# Generated by Django 6.0.3 on 2026-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_projectoutput_output_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoutput',
            name='output_type',
            field=models.CharField(choices=[('overview', 'Project Overview'), ('architecture', 'Architecture Explanation'), ('workflow', 'Workflow Explanation'), ('user_manual', 'User Manual'), ('class_diagram', 'Class Diagram'), ('object_diagram', 'Object Diagram'), ('component_diagram', 'Component Diagram'), ('composite_structure_diagram', 'Composite Structure Diagram'), ('package_diagram', 'Package Diagram'), ('deployment_diagram', 'Deployment Diagram'), ('profile_diagram', 'Profile Diagram'), ('usecase_diagram', 'Use Case Diagram'), ('activity_diagram', 'Activity Diagram'), ('state_diagram', 'State Machine Diagram'), ('sequence_diagram', 'Sequence Diagram'), ('communication_diagram', 'Communication Diagram'), ('interaction_overview_diagram', 'Interaction Overview Diagram'), ('timing_diagram', 'Timing Diagram'), ('er_diagram', 'Entity-Relationship Diagram (ERD)'), ('c4_context_diagram', 'C4 System Context Diagram'), ('workflow_flowchart', 'Workflow Flowchart'), ('mindmap', 'Mind Map'), ('project_structure', 'Project Structure (File Tree)')], max_length=30),
        ),
    ]
