# Generated by Django 5.0.14 on 2026-04-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_alter_projectoutput_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='agent_workers',
            field=models.IntegerField(default=1, help_text='Number of parallel AI agents used'),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_components',
            field=models.JSONField(blank=True, default=list, help_text='List of output components to generate. Empty means all.'),
        ),
    ]
