# Generated by Django 6.0.3 on 2026-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo_position',
            field=models.CharField(choices=[('left', 'Logo Left, Name Right'), ('right', 'Name Left, Logo Right')], default='right', max_length=10),
        ),
    ]
