# Generated by Django 6.0.3 on 2026-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_userprofile_logo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='logo_position',
            field=models.CharField(choices=[('left', 'Logo Left, Name Right'), ('right', 'Name Left, Logo Right'), ('center', 'Centered Stacked')], default='right', max_length=10),
        ),
    ]
