# Generated by Django 6.0.3 on 2026-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_alter_userprofile_logo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo_size',
            field=models.IntegerField(default=60, help_text='Height of logo in pixels'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_size',
            field=models.IntegerField(default=28, help_text='Font size of name in pixels'),
        ),
    ]
