# Generated by Django 6.0.3 on 2026-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_userprofile_logo_size_userprofile_name_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_font_size',
            field=models.IntegerField(default=11, help_text='Body text font size in pt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='footer_text',
            field=models.CharField(blank=True, default='', help_text='Custom footer text (leave blank for company name)', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_color',
            field=models.CharField(default='#4f46e5', help_text='Hex color for header accent', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_subtitle',
            field=models.CharField(blank=True, default='Comprehensive Documentation & Architecture Report', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header_title',
            field=models.CharField(blank=True, default='Project Analysis Report', help_text='Custom report title', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='heading_font_size',
            field=models.IntegerField(default=18, help_text='Section heading font size in px'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_page_numbers',
            field=models.BooleanField(default=True),
        ),
    ]
